"""Make column non-nullable

Revision ID: 4fa5edc2bf5f
Revises: f5a05741d438
Create Date: 2024-07-07 18:45:04.658208

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4fa5edc2bf5f'
down_revision: Union[str, None] = 'f5a05741d438'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rooms', sa.Column('quantity', sa.Integer(), nullable=False))
    op.alter_column('rooms', 'hotel_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('rooms', 'rooms_quantity')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rooms', sa.Column('rooms_quantity', sa.INTEGER(), autoincrement=False, nullable=False))
    op.alter_column('rooms', 'hotel_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('rooms', 'quantity')
    # ### end Alembic commands ###
